var txt = { 
	
	de: {
		title: 'Kamelrechner',
		headline: 'Kamelrechner',
		desc: 'Hier kannst du den Wert deiner Freundin, deines Freundes oder natürlich von dir selbst, in Kamelen berechnen. Hierzu benötigen wir aber erst ein paar Angaben zur Person.',
		headm: 'Wie viele Kamele ist dein Freund wert?',
		headf: 'Wie viele Kamele ist deine Freundin wert?',
		german: 'Deutsch',
		english: 'Englisch',
		age: 'Alter',
		height: 'Größe',
		haircolor: 'Haarfarbe',
		blonde: 'blond',
		brown: 'braun',
		black: 'schwarz',
		red: 'rot',
		grey: 'grau',
		hairlength: 'Haarlänge',
		long: 'lang',
		middle: 'mittel',
		short: 'kurz',
		bald: 'glatze',
		eyecolor: 'Augenfarbe',
		blue: 'blau',
		green: 'grün',
		brown: 'braun',
		beard: 'Bart',
		body: 'Oberkörper',
		boobs: 'Körbchengröße',
		figure: 'Figur',
		thin: 'dünn',
		sporty: 'sportlich',
		normal: 'normal',
		chubby: 'mollig',
		fat: 'dick',
		calculate: 'BERECHNEN',
		resultm1: 'Dein Freund ist',
		resultm2: 'Kamele wert.',
		resultf1: 'Deine Freundin ist',
		resultf2: 'Kamele wert.',
		again: 'NOCHMAL BERECHNEN?'
	}, 
	
	en: {
		title: 'Kamelrechner',
		headline: 'Kamelrechner',
		desc: 'Here you can calculate how many camels your girlfriend or boyfriend is worth. But first we need some information about the person.',
		headm: 'How many camels for your boyfriend?',
		headf: 'How many camels for your girlfriend?',
		german: 'German',
		english: 'English',
		age: 'Age',
		height: 'Height',
		haircolor: 'Haircolor',
		blonde: 'blonde',
		brown: 'brown',
		black: 'black',
		red: 'red',
		grey: 'grey',
		hairlength: 'Hairlength',
		long: 'long',
		middle: 'middle',
		short: 'short',
		bald: 'bald',
		blue: 'blue',
		eyecolor: 'Eyecolor',
		green: 'green',
		brown: 'brown',
		beard: 'Beard',
		body: 'Body',
		boobs: 'Körbchengröße',
		figure: 'Figure',
		thin: 'thin',
		sporty: 'sporty',
		normal: 'normal',
		chubby: 'chubby',
		fat: 'fat',
		calculate: 'CALCULATE',
		resultm1: 'Your boyfriend is worth',
		resultm2: 'camels.',
		resultf1: 'Your girlfriend is worth',
		resultf2: 'camels.',
		again: 'CALCULATE AGAIN?'
	}
};